apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "firewall.arkadeepsen.io/v1alpha1",
          "kind": "EbpfEgressFirewall",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "ebpf-egress-firewall-operator",
              "app.kubernetes.io/instance": "ebpfegressfirewall-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ebpfegressfirewall",
              "app.kubernetes.io/part-of": "ebpf-egress-firewall-operator"
            },
            "name": "ebpfegressfirewall-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "firewall.arkadeepsen.io/v1alpha1",
          "kind": "EbpfEgressFirewallFeature",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "ebpf-egress-firewall-operator",
              "app.kubernetes.io/instance": "ebpfegressfirewallfeature-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "ebpfegressfirewallfeature",
              "app.kubernetes.io/part-of": "ebpf-egress-firewall-operator"
            },
            "name": "ebpfegressfirewallfeature-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-12-23T23:50:12Z"
    operators.operatorframework.io/builder: operator-sdk-v1.29.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: ebpf-egress-firewall-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: EbpfEgressFirewallFeature is the Schema for the ebpfegressfirewallfeatures
        API
      displayName: Ebpf Egress Firewall Feature
      kind: EbpfEgressFirewallFeature
      name: ebpfegressfirewallfeatures.firewall.arkadeepsen.io
      version: v1alpha1
    - description: EbpfEgressFirewall describes the egress firewall rules for a Namespace.
        Traffic from pod will be checked against the rules. By default, if there are
        no EbpfEgressFirewall, or no rule matches the traffic, then the traffic will
        be allowed.
      displayName: Ebpf Egress Firewall
      kind: EbpfEgressFirewall
      name: ebpfegressfirewalls.firewall.arkadeepsen.io
      version: v1alpha1
  description: Egress Firewall based on eBPF
  displayName: eBPF Egress Firewall Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewallfeatures
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewallfeatures/finalizers
          verbs:
          - update
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewallfeatures/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewalls
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewalls/finalizers
          verbs:
          - update
        - apiGroups:
          - firewall.arkadeepsen.io
          resources:
          - ebpfegressfirewalls/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: ebpf-egress-firewall-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: ebpf-egress-firewall-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: ebpf-egress-firewall-operator
          control-plane: controller-manager
        name: ebpf-egress-firewall-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ebpf-egress-firewall-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: ebpf-egress-firewall-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: ebpf-egress-firewall-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - eBPF
  - firewall
  links:
  - name: Ebpf Egress Firewall Operator
    url: https://ebpf-egress-firewall-operator.domain
  maintainers:
  - email: arkadeep.sen8@gmail.com
    name: arkadeepsen
  maturity: alpha
  provider:
    name: Arkadeep Sen
  version: 0.0.1
