# permissions for end users to view ebpfegressfirewallfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ebpfegressfirewallfeature-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ebpf-egress-firewall-operator
    app.kubernetes.io/part-of: ebpf-egress-firewall-operator
    app.kubernetes.io/managed-by: kustomize
  name: ebpfegressfirewallfeature-viewer-role
rules:
- apiGroups:
  - firewall.arkadeepsen.io
  resources:
  - ebpfegressfirewallfeatures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - firewall.arkadeepsen.io
  resources:
  - ebpfegressfirewallfeatures/status
  verbs:
  - get
