apiVersion: firewall.arkadeepsen.io/v1alpha1
kind: EbpfEgressFirewallFeature
metadata:
  labels:
    app.kubernetes.io/name: ebpfegressfirewallfeature
    app.kubernetes.io/instance: ebpfegressfirewallfeature-sample
    app.kubernetes.io/part-of: ebpf-egress-firewall-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ebpf-egress-firewall-operator
  name: ebpfegressfirewallfeature-sample
spec:
  # TODO(user): Add fields here
