//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowRule) DeepCopyInto(out *AllowRule) {
	*out = *in
	in.CommonRule.DeepCopyInto(&out.CommonRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowRule.
func (in *AllowRule) DeepCopy() *AllowRule {
	if in == nil {
		return nil
	}
	out := new(AllowRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRule) DeepCopyInto(out *CommonRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]FirewallPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRule.
func (in *CommonRule) DeepCopy() *CommonRule {
	if in == nil {
		return nil
	}
	out := new(CommonRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DenyRule) DeepCopyInto(out *DenyRule) {
	*out = *in
	in.CommonRule.DeepCopyInto(&out.CommonRule)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DenyRule.
func (in *DenyRule) DeepCopy() *DenyRule {
	if in == nil {
		return nil
	}
	out := new(DenyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewall) DeepCopyInto(out *EbpfEgressFirewall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewall.
func (in *EbpfEgressFirewall) DeepCopy() *EbpfEgressFirewall {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfEgressFirewall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallFeature) DeepCopyInto(out *EbpfEgressFirewallFeature) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallFeature.
func (in *EbpfEgressFirewallFeature) DeepCopy() *EbpfEgressFirewallFeature {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfEgressFirewallFeature) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallFeatureList) DeepCopyInto(out *EbpfEgressFirewallFeatureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EbpfEgressFirewallFeature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallFeatureList.
func (in *EbpfEgressFirewallFeatureList) DeepCopy() *EbpfEgressFirewallFeatureList {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallFeatureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfEgressFirewallFeatureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallFeatureSpec) DeepCopyInto(out *EbpfEgressFirewallFeatureSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallFeatureSpec.
func (in *EbpfEgressFirewallFeatureSpec) DeepCopy() *EbpfEgressFirewallFeatureSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallFeatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallFeatureStatus) DeepCopyInto(out *EbpfEgressFirewallFeatureStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallFeatureStatus.
func (in *EbpfEgressFirewallFeatureStatus) DeepCopy() *EbpfEgressFirewallFeatureStatus {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallFeatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallList) DeepCopyInto(out *EbpfEgressFirewallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EbpfEgressFirewall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallList.
func (in *EbpfEgressFirewallList) DeepCopy() *EbpfEgressFirewallList {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EbpfEgressFirewallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallSpec) DeepCopyInto(out *EbpfEgressFirewallSpec) {
	*out = *in
	if in.AllowRules != nil {
		in, out := &in.AllowRules, &out.AllowRules
		*out = make([]AllowRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DenyRules != nil {
		in, out := &in.DenyRules, &out.DenyRules
		*out = make([]AllowRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallSpec.
func (in *EbpfEgressFirewallSpec) DeepCopy() *EbpfEgressFirewallSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfEgressFirewallStatus) DeepCopyInto(out *EbpfEgressFirewallStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfEgressFirewallStatus.
func (in *EbpfEgressFirewallStatus) DeepCopy() *EbpfEgressFirewallStatus {
	if in == nil {
		return nil
	}
	out := new(EbpfEgressFirewallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallPort) DeepCopyInto(out *FirewallPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallPort.
func (in *FirewallPort) DeepCopy() *FirewallPort {
	if in == nil {
		return nil
	}
	out := new(FirewallPort)
	in.DeepCopyInto(out)
	return out
}
